name: cse542a1
channels:
  - defaults
dependencies:
  - python=3.8.16
  - pip==23.3.1
  - pip:
    - cython==0.29.34
    - gym==0.19.0
    - gymnasium==0.29.1
    - gymnasium-robotics[mujoco-py]
    - gym-notices==0.0.8
    - matplotlib==3.7.1
    - mujoco==2.3.7
    - mujoco-py==2.1.2.14
    - numpy==1.24.3
    - packaging==23.1
    - pybullet==3.2.5
    - torch==1.13.1
    - torchvision
    - torchaudio
    - wheel==0.38.0